config:
  default: true

  # per-rule settings in alphabetical order
  # https://github.com/DavidAnson/markdownlint/tree/main/doc
  code-block-style:
    style: "fenced"                 # MD046
  line-length:                      # MD013
    code_blocks: false
    line_length: 100
    tables: false
  link-fragments:                   # MD051
    ignore_case: true

fix: true
